default_language_version:
  python: python3.12
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-json
      - id: check-yaml
      - id: check-toml
      - id: check-added-large-files
  - repo: local
    hooks:
      - id: ruff-check
        name: ruff-check
        language: system
        entry: poetry run ruff check
        types: [python]
        args:
        - --fix
      - id: ruff-format
        name: ruff-format
        language: system
        entry: poetry run ruff format
        types: [python]
